version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi --user www-data --bind 0.0.0.0:8010
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env