# Generated by Django 4.2.6 on 2023-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_alter_board_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
