# Generated by Django 4.2.6 on 2023-10-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0003_board_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='auto_draw',
            field=models.BooleanField(default=True),
        ),
    ]
