# Generated by Django 4.2.6 on 2023-11-24 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('balance', models.BigIntegerField(default=0)),
                ('available_balance', models.BigIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('onhold', 'On Hold'), ('inactive', 'In Active')], default='active', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_sender', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_receiver', to='wallet.wallet')),
                ('transaction_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
