# Generated by Django 4.2.6 on 2023-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_winner',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
